import { Platform, StyleSheet } from 'react-native';

// External styling: Beranda, saldo, transaksi, ringkasan, dan navigasi.
export const financeStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F3F4F6' },
  scrollContainer: { flexGrow: 1 },
  contentWrapper: { flex: 1, width: '100%', alignSelf: 'center' },
  contentWrapperTablet: { maxWidth: 900 },
  landscapeRow: { flexDirection: 'row', alignItems: 'flex-start' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24, position: 'relative', zIndex: 10 },
  appName: { fontSize: 16, fontWeight: '700', color: '#047857', marginBottom: 4, textTransform: 'uppercase', letterSpacing: 1 },
  greeting: { fontSize: 24, fontWeight: 'bold', color: '#111827' },
  profileBtn: { width: 48, height: 48, backgroundColor: '#FFFFFF', borderRadius: 24, justifyContent: 'center', alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  profileMenu: { position: 'absolute', right: 0, top: 56, width: 230, backgroundColor: '#FFFFFF', borderRadius: 16, padding: 14, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 12, elevation: 8 },
  profileMenuName: { fontSize: 15, fontWeight: '800', color: '#111827' },
  profileMenuEmail: { fontSize: 12, color: '#6B7280', marginTop: 3 },
  menuDivider: { height: 1, backgroundColor: '#E5E7EB', marginVertical: 10 },
  logoutButton: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 12, minHeight: 48 },
  logoutText: { color: '#B91C1C', fontWeight: '700' },
  mainCard: { backgroundColor: '#047857', borderRadius: 24, padding: 24, shadowColor: '#047857', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.25, shadowRadius: 16, elevation: 8, marginBottom: 24, width: '100%' },
  mainCardTablet: {},
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  cardTitle: { color: '#ECFDF5', fontSize: 16, fontWeight: '500', marginBottom: 8 },
  balanceText: { color: '#FFFFFF', fontSize: 32, fontWeight: 'bold', letterSpacing: 0.5 },
  cardDivider: { height: 1, backgroundColor: 'rgba(255,255,255,0.2)', marginBottom: 20 },
  cardStats: { flexDirection: 'row', justifyContent: 'space-between' },
  statItem: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  statItemCompact: { flexDirection: 'column', alignItems: 'flex-start', gap: 8 },
  statIconContainerIncome: { width: 40, height: 40, backgroundColor: '#D1FAE5', borderRadius: 20, justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  statIconContainerExpense: { width: 40, height: 40, backgroundColor: '#FEE2E2', borderRadius: 20, justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  statTextContainer: { flex: 1 },
  statTextContainerCompact: { width: '100%' },
  statLabel: { color: '#ECFDF5', fontSize: 14, marginBottom: 2 },
  statValue: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  actionContainer: { flexDirection: 'row', gap: 16, marginBottom: 32 },
  actionButton: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 16, minHeight: 52, borderRadius: 16, gap: 8, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  btnIncome: { backgroundColor: '#047857' },
  btnExpense: { backgroundColor: '#FFFFFF', borderWidth: 1.5, borderColor: '#FECACA' },
  actionButtonText: { fontSize: 16, fontWeight: '700', color: '#FFFFFF' },
  textExpense: { color: '#B91C1C' },
  sectionContainer: { marginBottom: 28 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  sectionTitle: { fontSize: 20, fontWeight: 'bold', color: '#111827' },
  transactionCount: { color: '#6B7280', fontSize: 13 },
  summaryCard: { backgroundColor: '#FFFFFF', borderRadius: 20, padding: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 },
  summaryCardGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16, padding: 20 },
  summaryItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 14 },
  summaryItemGrid: { flex: 1, minWidth: '40%', backgroundColor: '#F9FAFB', padding: 16, borderRadius: 16, flexDirection: 'column', alignItems: 'flex-start', gap: 8 },
  borderBottom: { borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  summaryItemLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  summaryIconContainer: { width: 44, height: 44, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  summaryItemTitle: { fontSize: 16, fontWeight: '600', color: '#1F2937', flex: 1 },
  summaryItemAmount: { fontSize: 16, fontWeight: '700', color: '#111827' },
  transactionItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#FFFFFF', padding: 16, borderRadius: 16, marginBottom: 12, minHeight: 64, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2 },
  transactionLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, marginRight: 12 },
  transactionIcon: { width: 48, height: 48, borderRadius: 24, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  transactionTextContainer: { flex: 1 },
  transactionTitle: { fontSize: 16, fontWeight: '700', color: '#111827', marginBottom: 4 },
  transactionCategory: { fontSize: 14, color: '#4B5563' },
  transactionSource: { fontSize: 12, color: '#6B7280', marginTop: 4 },
  errorText: { color: '#B91C1C', backgroundColor: '#FEF2F2', padding: 12, borderRadius: 12, marginVertical: 12, lineHeight: 20 },
  apiCard: { padding: 16, marginBottom: 24, backgroundColor: '#ECFDF5', borderRadius: 16, flexDirection: 'row', alignItems: 'center', gap: 12, flexWrap: 'wrap' },
  apiTitle: { fontSize: 15, fontWeight: '700', color: '#065F46' },
  apiDescription: { fontSize: 13, color: '#374151', marginTop: 6, lineHeight: 20 },
  refreshButton: { minHeight: 48, paddingHorizontal: 12, gap: 6, alignItems: 'center', justifyContent: 'center' },
  refreshText: { color: '#047857', fontSize: 14, fontWeight: '700' },
  profileCard: { padding: 24, backgroundColor: '#FFFFFF', borderRadius: 20, gap: 16 },
  profileDetail: { fontSize: 16, color: '#4B5563', lineHeight: 24 },
  guideButton: { minHeight: 48, justifyContent: 'center' },
  transactionAmount: { fontSize: 16, fontWeight: 'bold' },
  emptyCard: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 28, alignItems: 'center', gap: 8 },
  emptyText: { color: '#6B7280' },
  bottomSpacer: { height: 100 },
  bottomNavContainer: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#E5E7EB', shadowColor: '#000', shadowOffset: { width: 0, height: -4 }, shadowOpacity: 0.1, shadowRadius: 12, elevation: 16 },
  bottomNav: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 24, paddingBottom: Platform.OS === 'ios' ? 24 : 12, width: '100%', alignSelf: 'center' },
  navItem: { alignItems: 'center', justifyContent: 'center', flex: 1, minHeight: 48 },
  navLabel: { fontSize: 14, marginTop: 4, color: '#4B5563', fontWeight: '600' },
  navLabelActive: { color: '#047857', fontWeight: '700' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
  modalCard: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, maxHeight: '90%', paddingBottom: Platform.OS === 'ios' ? 36 : 24 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20 },
  modalTitle: { fontSize: 22, fontWeight: '800', color: '#111827' },
  modalSubtitle: { color: '#6B7280', marginTop: 4 },
  closeButton: { width: 48, height: 48, borderRadius: 24, backgroundColor: '#F3F4F6', alignItems: 'center', justifyContent: 'center' },
  label: { fontSize: 13, fontWeight: '700', color: '#374151', marginBottom: 7, marginTop: 8 },
  formInput: { borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 12, minHeight: 50, paddingHorizontal: 14, fontSize: 16, color: '#111827', backgroundColor: '#F9FAFB' },
  primarySaveButton: { backgroundColor: '#047857', minHeight: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginTop: 20 },
  primarySaveText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
});
